# Site settings
title: Your awesome title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "http://surunzi.github.io/WebVN"
url: ""
exclude: ["run.bat", "build.bat", "minify.bat", "gulpfile.js", "node_modules", "package.json"]

# Build settings
markdown: kramdown
permalink: pretty
